<a href="https://colab.research.google.com/github/Gowtham-Pentela/NLP/blob/main/Practise_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install poetry
!git clone "https://github.com/PacktPublishing/Python-Natural-Language-Processing-Cookbook-Second-Edition.git"


fatal: destination path 'Python-Natural-Language-Processing-Cookbook-Second-Edition' already exists and is not an empty directory.


In [2]:
path = "/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/"


In [3]:
%run -i '/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/util/file_utils.ipynb'



In [4]:
!pip install -r "/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/requirements.txt"

Ignoring appnope: markers 'python_version >= "3.9" and python_version < "4.0" and platform_system == "Darwin" or python_version >= "3.9" and python_version < "4.0" and sys_platform == "darwin"' don't match your environment
Ignoring exceptiongroup: markers 'python_version >= "3.9" and python_version < "3.11"' don't match your environment
Ignoring importlib-metadata: markers 'python_version >= "3.9" and python_version < "3.10"' don't match your environment
Ignoring importlib-resources: markers 'python_version >= "3.9" and python_version < "3.10"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32" and platform_python_implementation != "PyPy" and python_version >= "3.9" and python_version < "4.0"' don't match your environment
Ignoring pywinpty: markers 'python_version >= "3.9" and python_version < "4.0" and os_name == "nt"' don't match your environment
Ignoring tomli: markers 'python_version >= "3.9" and python_full_version <= "3.11.0a6"' don't match your envir

In [5]:
sherlock_text_path =path+"data/sherlock_holmes_1.txt"
def read_text_file(filename):
  file = open(filename, "r", encoding="utf-8")
  return file.read()
sherlock_text = read_text_file(sherlock_text_path)
print(sherlock_text)

To Sherlock Holmes she is always _the_ woman. I have seldom heard him
mention her under any other name. In his eyes she eclipses and
predominates the whole of her sex. It was not that he felt any emotion
akin to love for Irene Adler. All emotions, and that one particularly,
were abhorrent to his cold, precise but admirably balanced mind. He
was, I take it, the most perfect reasoning and observing machine that
the world has seen, but as a lover he would have placed himself in a
false position. He never spoke of the softer passions, save with a gibe
and a sneer. They were admirable things for the observer—excellent for
drawing the veil from men’s motives and actions. But for the trained
reasoner to admit such intrusions into his own delicate and finely
adjusted temperament was to introduce a distracting factor which might
throw a doubt upon all his mental results. Grit in a sensitive
instrument, or a crack in one of his own high-power lenses, would not
be more disturbing than a strong em

In [6]:
import nltk
#nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource
tokenizer = nltk.data.load("tokenizers/punkt/english.pickle")
sentences_nltk = tokenizer.tokenize(sherlock_text)
print(sentences_nltk)

['To Sherlock Holmes she is always _the_ woman.', 'I have seldom heard him\nmention her under any other name.', 'In his eyes she eclipses and\npredominates the whole of her sex.', 'It was not that he felt any emotion\nakin to love for Irene Adler.', 'All emotions, and that one particularly,\nwere abhorrent to his cold, precise but admirably balanced mind.', 'He\nwas, I take it, the most perfect reasoning and observing machine that\nthe world has seen, but as a lover he would have placed himself in a\nfalse position.', 'He never spoke of the softer passions, save with a gibe\nand a sneer.', 'They were admirable things for the observer—excellent for\ndrawing the veil from men’s motives and actions.', 'But for the trained\nreasoner to admit such intrusions into his own delicate and finely\nadjusted temperament was to introduce a distracting factor which might\nthrow a doubt upon all his mental results.', 'Grit in a sensitive\ninstrument, or a crack in one of his own high-power lenses, wou

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [7]:
print(len(sentences_nltk))

11


In [8]:
words = nltk.tokenize.word_tokenize(sherlock_text)
print(words)
print(len(words))

['To', 'Sherlock', 'Holmes', 'she', 'is', 'always', '_the_', 'woman', '.', 'I', 'have', 'seldom', 'heard', 'him', 'mention', 'her', 'under', 'any', 'other', 'name', '.', 'In', 'his', 'eyes', 'she', 'eclipses', 'and', 'predominates', 'the', 'whole', 'of', 'her', 'sex', '.', 'It', 'was', 'not', 'that', 'he', 'felt', 'any', 'emotion', 'akin', 'to', 'love', 'for', 'Irene', 'Adler', '.', 'All', 'emotions', ',', 'and', 'that', 'one', 'particularly', ',', 'were', 'abhorrent', 'to', 'his', 'cold', ',', 'precise', 'but', 'admirably', 'balanced', 'mind', '.', 'He', 'was', ',', 'I', 'take', 'it', ',', 'the', 'most', 'perfect', 'reasoning', 'and', 'observing', 'machine', 'that', 'the', 'world', 'has', 'seen', ',', 'but', 'as', 'a', 'lover', 'he', 'would', 'have', 'placed', 'himself', 'in', 'a', 'false', 'position', '.', 'He', 'never', 'spoke', 'of', 'the', 'softer', 'passions', ',', 'save', 'with', 'a', 'gibe', 'and', 'a', 'sneer', '.', 'They', 'were', 'admirable', 'things', 'for', 'the', 'observe

In [9]:
import spacy
!python -m spacy download en_core_web_sm
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 35.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.7/400.7 MB 1.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [10]:
nlp = spacy.load("en_core_web_sm")

In [11]:
doc = nlp(sherlock_text)

In [12]:
sentences_spacy = [sentence.text for sentence in doc.sents]
print(sentences_spacy)
print(len(sentences_spacy))

['To Sherlock Holmes she is always _the_ woman.', 'I have seldom heard him\nmention her under any other name.', 'In his eyes she eclipses and\npredominates the whole of her sex.', 'It was not that he felt any emotion\nakin to love for Irene Adler.', 'All emotions, and that one particularly,\nwere abhorrent to his cold, precise but admirably balanced mind.', 'He\nwas, I take it, the most perfect reasoning and observing machine that\nthe world has seen, but as a lover he would have placed himself in a\nfalse position.', 'He never spoke of the softer passions, save with a gibe\nand a sneer.', 'They were admirable things for the observer—excellent for\ndrawing the veil from men’s motives and actions.', 'But for the trained\nreasoner to admit such intrusions into his own delicate and finely\nadjusted temperament was to introduce a distracting factor which might\nthrow a doubt upon all his mental results.', 'Grit in a sensitive\ninstrument, or a crack in one of his own high-power lenses, wou

In [13]:
spacy_words = [token.text for token in doc]
print(spacy_words)
print(len(spacy_words))

['To', 'Sherlock', 'Holmes', 'she', 'is', 'always', '_', 'the', '_', 'woman', '.', 'I', 'have', 'seldom', 'heard', 'him', '\n', 'mention', 'her', 'under', 'any', 'other', 'name', '.', 'In', 'his', 'eyes', 'she', 'eclipses', 'and', '\n', 'predominates', 'the', 'whole', 'of', 'her', 'sex', '.', 'It', 'was', 'not', 'that', 'he', 'felt', 'any', 'emotion', '\n', 'akin', 'to', 'love', 'for', 'Irene', 'Adler', '.', 'All', 'emotions', ',', 'and', 'that', 'one', 'particularly', ',', '\n', 'were', 'abhorrent', 'to', 'his', 'cold', ',', 'precise', 'but', 'admirably', 'balanced', 'mind', '.', 'He', '\n', 'was', ',', 'I', 'take', 'it', ',', 'the', 'most', 'perfect', 'reasoning', 'and', 'observing', 'machine', 'that', '\n', 'the', 'world', 'has', 'seen', ',', 'but', 'as', 'a', 'lover', 'he', 'would', 'have', 'placed', 'himself', 'in', 'a', '\n', 'false', 'position', '.', 'He', 'never', 'spoke', 'of', 'the', 'softer', 'passions', ',', 'save', 'with', 'a', 'gibe', '\n', 'and', 'a', 'sneer', '.', 'They

In [14]:
print(set(spacy_words)-set(words))

{'power', '-', 'excellent', '\n', '’s', 'observer', 'high', '_', '—'}


In [15]:
import time
def split_into_sentences_nltk(text):
  sentences = tokenizer.tokenize(text)
  return sentences
def split_into_sentences_spacy(text):
  doc = nlp(text)
  sentences = [sentence.text for sentence in doc.sents]
  return sentences
start = time.time()
split_into_sentences_nltk(sherlock_text)
print(f"NLTK: {time.time() - start} s")
start = time.time()
split_into_sentences_spacy(sherlock_text)
print(f"spaCy: {time.time() - start} s")

NLTK: 0.0008172988891601562 s
spaCy: 0.3524951934814453 s


In [16]:

nltk.download('stopwords')
%run -i '/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/util/lang_utils.ipynb'
%run -i '/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/util/file_utils.ipynb'

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [17]:
def pos_tag_spacy(text, model):
  doc = model(text)
  words = [token.text for token in doc]
  pos = [token.pos_ for token in doc]
  return list(zip(words, pos))

In [18]:
words_with_pos = pos_tag_spacy(sherlock_text, small_model)
print(words_with_pos)

[('To', 'ADP'), ('Sherlock', 'PROPN'), ('Holmes', 'PROPN'), ('she', 'PRON'), ('is', 'AUX'), ('always', 'ADV'), ('_', 'PUNCT'), ('the', 'DET'), ('_', 'PROPN'), ('woman', 'NOUN'), ('.', 'PUNCT'), ('I', 'PRON'), ('have', 'AUX'), ('seldom', 'ADV'), ('heard', 'VERB'), ('him', 'PRON'), ('\n', 'SPACE'), ('mention', 'VERB'), ('her', 'PRON'), ('under', 'ADP'), ('any', 'DET'), ('other', 'ADJ'), ('name', 'NOUN'), ('.', 'PUNCT'), ('In', 'ADP'), ('his', 'PRON'), ('eyes', 'NOUN'), ('she', 'PRON'), ('eclipses', 'VERB'), ('and', 'CCONJ'), ('\n', 'SPACE'), ('predominates', 'VERB'), ('the', 'DET'), ('whole', 'NOUN'), ('of', 'ADP'), ('her', 'PRON'), ('sex', 'NOUN'), ('.', 'PUNCT'), ('It', 'PRON'), ('was', 'AUX'), ('not', 'PART'), ('that', 'SCONJ'), ('he', 'PRON'), ('felt', 'VERB'), ('any', 'DET'), ('emotion', 'NOUN'), ('\n', 'SPACE'), ('akin', 'ADJ'), ('to', 'PART'), ('love', 'VERB'), ('for', 'ADP'), ('Irene', 'PROPN'), ('Adler', 'PROPN'), ('.', 'PUNCT'), ('All', 'DET'), ('emotions', 'NOUN'), (',', 'PUNC

In [19]:
def pos_tag_nltk(text):
  words = word_tokenize_nltk(text)
  words_with_pos = nltk.pos_tag(words)
  return words_with_pos

In [20]:
nltk.download('averaged_perceptron_tagger_eng')


[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [21]:
words_with_pos = pos_tag_nltk(sherlock_text)
print(words_with_pos)

[('To', 'TO'), ('Sherlock', 'NNP'), ('Holmes', 'NNP'), ('she', 'PRP'), ('is', 'VBZ'), ('always', 'RB'), ('_the_', 'JJ'), ('woman', 'NN'), ('.', '.'), ('I', 'PRP'), ('have', 'VBP'), ('seldom', 'VBN'), ('heard', 'RB'), ('him', 'PRP'), ('mention', 'VB'), ('her', 'PRP'), ('under', 'IN'), ('any', 'DT'), ('other', 'JJ'), ('name', 'NN'), ('.', '.'), ('In', 'IN'), ('his', 'PRP$'), ('eyes', 'NNS'), ('she', 'PRP'), ('eclipses', 'VBZ'), ('and', 'CC'), ('predominates', 'VBZ'), ('the', 'DT'), ('whole', 'NN'), ('of', 'IN'), ('her', 'PRP$'), ('sex', 'NN'), ('.', '.'), ('It', 'PRP'), ('was', 'VBD'), ('not', 'RB'), ('that', 'IN'), ('he', 'PRP'), ('felt', 'VBD'), ('any', 'DT'), ('emotion', 'NN'), ('akin', 'NN'), ('to', 'TO'), ('love', 'VB'), ('for', 'IN'), ('Irene', 'NNP'), ('Adler', 'NNP'), ('.', '.'), ('All', 'DT'), ('emotions', 'NNS'), (',', ','), ('and', 'CC'), ('that', 'IN'), ('one', 'CD'), ('particularly', 'RB'), (',', ','), ('were', 'VBD'), ('abhorrent', 'JJ'), ('to', 'TO'), ('his', 'PRP$'), ('co

**Removing STOP Words**


In [22]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [24]:
words = word_tokenize_nltk(sherlock_text)
print(len(words))

230


In [25]:
words = [word for word in words if word not in stopwords.words('english')]
print(len(words))

129


**Chapter2 Grammar**

#### <i>Difference between Singular and Plural </i>

In [26]:
sample_text = "I have 5 birds"
doc = small_model(sample_text)
for token in doc:
  if (token.pos_ == "NOUN" and token.lemma_ != token.text):
    print(token.text, "plural")

birds plural


In [27]:
for token in doc:
  print(token,token.morph.get("Number"))

I ['Sing']
have []
5 []
birds ['Plur']


In [28]:
class Noun_number(Enum):
  SINGULAR = 1
  PLURAL = 2

In [29]:
def get_nouns_number(text, model, method="lemma"):
  nouns = []
  doc = model(text)
  for token in doc:
    if (token.pos_ == "NOUN"):
      if method == "lemma":
        if token.lemma_ != token.text:
          nouns.append((token.text,Noun_number.PLURAL))
        else:
          nouns.append((token.text,Noun_number.SINGULAR))
      elif method == "morph":
        if token.morph.get("Number") == "Sing":
          nouns.append((token.text,Noun_number.PLURAL))
        else:
          nouns.append((token.text,Noun_number.SINGULAR))
  print(nouns)
  return nouns

In [30]:
text = "Three geese crossed the road"
nouns = get_nouns_number(text, small_model, "morph")
nouns = get_nouns_number(text, small_model, "lemma")

[('geese', <Noun_number.SINGULAR: 1>), ('road', <Noun_number.SINGULAR: 1>)]
[('geese', <Noun_number.PLURAL: 2>), ('road', <Noun_number.SINGULAR: 1>)]


In [31]:
from textblob import TextBlob
texts = ["book", "goose", "pen", "point", "deer"]
blob_objs = [TextBlob(text) for text in texts]
plurals = [blob_obj.words.pluralize()[0] for blob_obj in blob_objs]
print("Plurals:",plurals)
blob_objs = [TextBlob(text) for text in plurals]
singulars = [blob_obj.words.singularize()[0] for blob_obj in blob_objs]
print(singulars)

Plurals: ['books', 'geese', 'pens', 'points', 'deer']
['book', 'goose', 'pen', 'point', 'deer']


#### Finding root of the sentence

In [32]:
sentence = 'I have seldom heard him mention her under any other name.'
def print_dependencies(sentence, model):
  doc = model(sentence)
  for token in doc:
    print(token.text, "\t", token.dep_, "\t",spacy.explain(token.dep_))
print_dependencies(sentence, small_model)

I 	 nsubj 	 nominal subject
have 	 aux 	 auxiliary
seldom 	 advmod 	 adverbial modifier
heard 	 ROOT 	 root
him 	 nsubj 	 nominal subject
mention 	 ccomp 	 clausal complement
her 	 dobj 	 direct object
under 	 prep 	 prepositional modifier
any 	 det 	 determiner
other 	 amod 	 adjectival modifier
name 	 pobj 	 object of preposition
. 	 punct 	 punctuation


In [33]:
def print_ancestors(sentence, model):
  doc = model(sentence)
  for token in doc:
    print(token.text, [t.text for t in token.ancestors])
print_ancestors(sentence, small_model)

I ['heard']
have ['heard']
seldom ['heard']
heard []
him ['mention', 'heard']
mention ['heard']
her ['mention', 'heard']
under ['mention', 'heard']
any ['name', 'under', 'mention', 'heard']
other ['name', 'under', 'mention', 'heard']
name ['under', 'mention', 'heard']
. ['heard']


### Childeren (Dependents)

In [34]:
def print_children(sentence, model):
  doc = model(sentence)
  for token in doc:
    print(token.text,[t.text for t in token.children])
print_children(sentence, small_model)

I []
have []
seldom []
heard ['I', 'have', 'seldom', 'mention', '.']
him []
mention ['him', 'her', 'under']
her []
under ['name']
any []
other []
name ['any', 'other']
. []


#### Left and Right Dependents

In [35]:
def print_lefts_and_rights(sentence, model):
  doc = model(sentence)
  for token in doc:
    print(token.text,[t.text for t in token.lefts],[t.text for t in token.rights])
print_lefts_and_rights(sentence, small_model)

I [] []
have [] []
seldom [] []
heard ['I', 'have', 'seldom'] ['mention', '.']
him [] []
mention ['him'] ['her', 'under']
her [] []
under [] ['name']
any [] []
other [] []
name ['any', 'other'] []
. [] []


#### Extracting Noun Chunks

In [36]:
def print_noun_chunks(text, model):
  doc = model(text)
  for noun_chunk in doc.noun_chunks:
    print(noun_chunk.text)
print_noun_chunks(sherlock_text, small_model)

Sherlock Holmes
she
the_ woman
I
him
her
any other name
his eyes
she
the whole
her sex
It
he
any emotion
Irene Adler
All emotions
his cold, precise but admirably balanced mind
He
I
it
the most perfect reasoning
machine
that
the world
a lover
he
himself
a
false position
He
the softer passions
a gibe
a sneer
They
admirable things
the observer
the veil
men’s motives
actions
the trained
reasoner
such intrusions
his own delicate and finely
adjusted temperament
a distracting factor
which
a doubt
all his mental results
Grit
a sensitive
instrument
a crack
his own high-power lenses
a strong emotion
a nature
his
one woman
him
that woman
the late Irene
Adler
dubious and questionable memory


In [37]:
def explore_properties(sentence, model):
  doc = model(sentence)
  other_span = "emotions"
  other_doc = model(other_span)
  for noun_chunk in doc.noun_chunks:
    print(noun_chunk.text)
    print("Noun chunk start and end", "\t",noun_chunk.start, "\t", noun_chunk.end)
    print("Noun chunk sentence:", noun_chunk.sent)
    print("Noun chunk root:", noun_chunk.root.text)
    print(f"Noun chunk similarity to '{other_span}'",noun_chunk.similarity(other_doc))
  print(f"Similarity of the sentence '{sentence}' to '{other_span}':",doc.similarity(other_doc))
sentence = "All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind."
explore_properties(sentence, small_model)

All emotions
Noun chunk start and end 	 0 	 2
Noun chunk sentence: All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind.
Noun chunk root: emotions
Noun chunk similarity to 'emotions' 0.5081886649131775
his cold, precise but admirably balanced mind
Noun chunk start and end 	 11 	 19
Noun chunk sentence: All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind.
Noun chunk root: mind
Noun chunk similarity to 'emotions' 0.012711606919765472
Similarity of the sentence 'All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind.' to 'emotions': 0.10214047878980637


/tmp/ipykernel_41844/3781881625.py:10: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Span.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print(f"Noun chunk similarity to '{other_span}'",noun_chunk.similarity(other_doc))
/tmp/ipykernel_41844/3781881625.py:11: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always

#### Finding Patterns

In [38]:
from spacy.matcher import Matcher
matcher = Matcher(small_model.vocab)
patterns = [
[{"POS": "VERB"}],
[{"POS": "AUX"}, {"POS": "VERB"}],
[{"POS": "AUX"}, {"POS": "ADJ"}],
[{"POS": "AUX"}, {"POS": "VERB"}, {"POS": "ADP"}]
]
matcher.add("Verb", patterns)
doc = small_model(sherlock_text)
matches = matcher(doc)
for match_id, start, end in matches:
  string_id = small_model.vocab.strings[match_id]
  span = doc[start:end]
  print(match_id, string_id, start, end, span.text)

14677086776663181681 Verb 14 15 heard
14677086776663181681 Verb 17 18 mention
14677086776663181681 Verb 28 29 eclipses
14677086776663181681 Verb 31 32 predominates
14677086776663181681 Verb 43 44 felt
14677086776663181681 Verb 49 50 love
14677086776663181681 Verb 63 65 were abhorrent
14677086776663181681 Verb 80 81 take
14677086776663181681 Verb 88 89 observing
14677086776663181681 Verb 94 96 has seen
14677086776663181681 Verb 95 96 seen
14677086776663181681 Verb 103 105 have placed
14677086776663181681 Verb 104 105 placed
14677086776663181681 Verb 114 115 spoke
14677086776663181681 Verb 120 121 save
14677086776663181681 Verb 130 132 were admirable
14677086776663181681 Verb 140 141 drawing
14677086776663181681 Verb 153 154 trained
14677086776663181681 Verb 157 158 admit
14677086776663181681 Verb 167 168 adjusted
14677086776663181681 Verb 171 172 introduce
14677086776663181681 Verb 178 179 throw
14677086776663181681 Verb 228 229 was


#### Capturing Semantics

In [39]:
from datasets import load_dataset
train_dataset = load_dataset("rotten_tomatoes",split="train[:15%]+train[-15%:]")
test_dataset = load_dataset("rotten_tomatoes",split="test[:15%]+test[-15%:]")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [40]:
print(len(train_dataset))
print(len(test_dataset))

2560
320


In [41]:
class POS_vectorizer:
  def __init__(self, spacy_model):
    self.model = spacy_model
  def vectorize(self, input_text):
    doc = self.model(input_text)
    vector = []
    vector.append(len(doc))
    pos = {"VERB":0, "NOUN":0, "PROPN":0, "ADJ":0,
    "ADV":0, "AUX":0, "PRON":0, "NUM":0, "PUNCT":0}
    for token in doc:
      if token.pos_ in pos:
        pos[token.pos_] += 1
    vector_values = list(pos.values())
    vector = vector + vector_values
    return vector
sample_text = train_dataset[0]["text"]
vectorizer = POS_vectorizer(small_model)
vector = vectorizer.vectorize(sample_text)

In [42]:
print(sample_text)
print(vector)

the rock is destined to be the 21st century's new " conan " and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal .
[38, 3, 8, 2, 5, 1, 3, 1, 0, 5]


In [43]:
import pandas as pd
import numpy as np
train_df = train_dataset.to_pandas()
train_df.sample(frac=1)
test_df = test_dataset.to_pandas()
train_df["vector"] = train_df["text"].apply(
lambda x: vectorizer.vectorize(x))
test_df["vector"] = test_df["text"].apply(
lambda x: vectorizer.vectorize(x))
X_train = np.stack(train_df["vector"].values, axis=0)
X_test = np.stack(test_df["vector"].values, axis=0)
y_train = train_df["label"].to_numpy()
y_test = test_df["label"].to_numpy()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
clf = LogisticRegression(C=0.1)
clf = clf.fit(X_train, y_train)
test_df["prediction"] = test_df["vector"].apply(lambda x: clf.predict([x])[0])
print(classification_report(test_df["label"],
test_df["prediction"]))

              precision    recall  f1-score   support

           0       0.58      0.56      0.57       160
           1       0.58      0.59      0.58       160

    accuracy                           0.58       320
   macro avg       0.58      0.58      0.58       320
weighted avg       0.58      0.58      0.58       320



#### Vectorize the text

In [44]:
from datasets import load_dataset
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
def load_train_test_dataset_pd():
  train_dataset = load_dataset("rotten_tomatoes",split="train[:15%]+train[-15%:]")
  test_dataset = load_dataset("rotten_tomatoes",split="test[:15%]+test[-15%:]")
  train_df = train_dataset.to_pandas()
  train_df.sample(frac=1)
  test_df = test_dataset.to_pandas()
  return (train_df, test_df)

#Vectorize
def create_train_test_data(train_df, test_df, vectorize):
  train_df["vector"] = train_df["text"].apply(lambda x: vectorize(x))
  test_df["vector"] = test_df["text"].apply(lambda x: vectorize(x))
  X_train = np.stack(train_df["vector"].values, axis=0)
  X_test = np.stack(test_df["vector"].values, axis=0)
  y_train = train_df["label"].to_numpy()
  y_test = test_df["label"].to_numpy()
  return (X_train, X_test, y_train, y_test)

def train_classifier(X_train, y_train):
  clf = LogisticRegression(C=0.1)
  clf = clf.fit(X_train, y_train)
  return clf

def test_classifier(test_df, clf):
  test_df["prediction"] = test_df["vector"].apply(lambda x: clf.predict([x])[0])
  print(classification_report(test_df["label"], test_df["prediction"]))

#### Bag of Words

In [45]:
%run -i "/content/Python-Natural-Language-Processing-Cookbook-Second-Edition/util/util_simple_classifier.ipynb"
from sklearn.feature_extraction.text import CountVectorizer
import sys
(train_df, test_df) = load_train_test_dataset_pd()
vectorizer = CountVectorizer(max_df=0.4)
X = vectorizer.fit_transform(train_df["text"])
print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 39134 stored elements and shape (2560, 8856)>
  Coords	Values
  (0, 6578)	1
  (0, 4219)	1
  (0, 2106)	1
  (0, 8000)	2
  (0, 717)	1
  (0, 42)	1
  (0, 1280)	1
  (0, 5260)	1
  (0, 1607)	1
  (0, 7889)	1
  (0, 3630)	1
  (0, 3406)	1
  (0, 4759)	1
  (0, 7345)	1
  (0, 2707)	1
  (0, 3476)	1
  (0, 7883)	1
  (0, 487)	1
  (0, 6769)	1
  (0, 4269)	1
  (0, 1441)	1
  (0, 8405)	1
  (0, 1889)	1
  (0, 5466)	1
  (0, 7461)	1
  :	:
  (2557, 5905)	1
  (2557, 3595)	1
  (2557, 6745)	1
  (2557, 1023)	1
  (2557, 5259)	1
  (2558, 8000)	1
  (2558, 5331)	1
  (2558, 6733)	1
  (2558, 970)	1
  (2558, 4150)	1
  (2558, 874)	1
  (2559, 4219)	1
  (2559, 5128)	1
  (2559, 285)	1
  (2559, 5292)	1
  (2559, 6278)	1
  (2559, 5326)	1
  (2559, 7929)	1
  (2559, 3336)	1
  (2559, 5622)	1
  (2559, 6748)	1
  (2559, 8629)	1
  (2559, 7915)	1
  (2559, 1679)	1
  (2559, 5904)	1


In [46]:
dense_matrix = X.todense()
print(dense_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [47]:
print(vectorizer.get_feature_names_out())
print(len(vectorizer.get_feature_names_out()))

['10' '100' '101' ... 'zone' 'ótimo' 'últimos']
8856


In [48]:
print(vectorizer.get_stop_words())

None


In [49]:
first_review = test_df['text'].iat[0]
print(first_review)

lovingly photographed in the manner of a golden book sprung to life , stuart little 2 manages sweetness largely without stickiness .


In [50]:
sparse_vector = vectorizer.transform([first_review])
print(sparse_vector)
dense_vector = sparse_vector.todense()
np.set_printoptions(threshold=sys.maxsize)
print(dense_vector)
np.set_printoptions(threshold=False)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 13 stored elements and shape (1, 8856)>
  Coords	Values
  (0, 955)	1
  (0, 3968)	1
  (0, 4451)	1
  (0, 4562)	1
  (0, 4622)	1
  (0, 4688)	1
  (0, 4779)	1
  (0, 4792)	1
  (0, 5764)	1
  (0, 7547)	1
  (0, 7715)	1
  (0, 8000)	1
  (0, 8734)	1
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [51]:
vectorizer = CountVectorizer(max_df=300)
X = vectorizer.fit_transform(train_df["text"])
print(vectorizer.stop_words)

None


In [52]:
vectorizer = CountVectorizer(stop_words=['the', 'this',
'these', 'in', 'at', 'for'])
X = vectorizer.fit_transform(train_df["text"])

In [53]:
vectorizer = CountVectorizer(max_df=0.8)
(train_df, test_df) = load_train_test_dataset_pd()
X = vectorizer.fit_transform(train_df["text"])
vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
(X_train, X_test, y_train, y_test) = create_train_test_data(
train_df, test_df, vectorize)
clf = train_classifier(X_train, y_train)
test_classifier(test_df, clf)

              precision    recall  f1-score   support

           0       0.74      0.72      0.73       160
           1       0.73      0.74      0.74       160

    accuracy                           0.73       320
   macro avg       0.73      0.73      0.73       320
weighted avg       0.73      0.73      0.73       320



#### NGram Models

In [54]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2), max_df=0.8)
X = bigram_vectorizer.fit_transform(train_df["text"])
print(bigram_vectorizer.get_feature_names_out())
print(len(bigram_vectorizer.get_feature_names_out()))

['10' '10 inch' '10 set' ... 'ótimo esforço' 'últimos' 'últimos tiempos']
40552


In [55]:
first_review = test_df['text'].iat[0]
dense_vector = bigram_vectorizer.transform(
[first_review]).todense()
print(dense_vector)

[[0 0 0 ... 0 0 0]]


In [56]:
vectorize = lambda x: vectorizer.transform([x]).toarray()[0]
(X_train, X_test, y_train, y_test) = create_train_test_data(
train_df, test_df, vectorize)
clf = train_classifier(X_train, y_train)
test_classifier(test_df, clf)

              precision    recall  f1-score   support

           0       0.74      0.72      0.73       160
           1       0.73      0.74      0.74       160

    accuracy                           0.73       320
   macro avg       0.73      0.73      0.73       320
weighted avg       0.73      0.73      0.73       320



###### TF = (Number of times a term appears in the document)/(Total number of words in the document)

##### IDF = (Total number of documents)/ (Number of documents where term occurs)


***TF - IDF = TF * IDF***


